((nil . ((indent-tabs-mode . nil)
         (fill-column . 80)
         (mode . auto-fill)))
 (c-mode . ((c-file-style . "linux")
            (c-basic-offset . 4)
            (mode . flymake)))
 (c++-mode . ((c-file-style . "linux")
            (c-basic-offset . 4)
            (mode . flymake))))
