name: Full C/C++ CI

on:
  push:
    branches: [ master, smoke ]
  pull_request:
    branches: [ master, smoke ]

jobs:
  full:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        MAKE:
          - lscpu
          - make -j4 O0=1 SANITIZE=1 LONG=1
          - make -j4 O1=1 SANITIZE=1 LONG=1
          - make -j4 Os=1 SANITIZE=1 LONG=1
          - make -j4 O2=1 SANITIZE=1
          - make -j4 O3=1 SANITIZE=1
          - make -j4 Ofast=1 SANITIZE=1
          - make -j4 O0=1 LONG=1
          - make -j4 O1=1 LONG=1
          - make -j4 O2=1 LONG=1
          - make -j4 O3=1 LONG=1
          - make -j4 Os=1 LONG=1
          - make -j4 Ofast=1 LONG=1
          - make -j4 CC=gcc\ -std=c99
          - make -j4 CC=gcc\ -std=c11
          - make -j4 CC='clang -std=c11' CXX='clang++-11 -stdlib=libc++'
          - make -j4 CXX='clang++-11 -std=c++2a -stdlib=libc++'
          - make examples SANITIZE=1
          - make perf
    steps:
    - if: ${{ contains(matrix.MAKE, 'O0=1 SANITIZE=1 LONG=1') }}
      name: setup cbmc
      run: sudo apt install -y --no-install-recommends cbmc
    # needed for libc++ since the Ubuntu 20.04.2 update (image version 20210315.1)
    # https://askubuntu.com/questions/1211743/clang-doesnt-find-c-stdlib-on-my-ubuntu-18-04-but-it-does-on-a-brand-new-ins
    # variant 1: downgrade clang++ to matching g++ (= 11)
    - if: ${{ contains(matrix.MAKE, 'libc++') }}
      run: |
        sudo apt-get install clang++-11 libc++-11-dev libc++abi-11-dev
        clang++ --version
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-11 100
        clang++ --version
        g++ --version
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run:  ${{ matrix.MAKE }}
      timeout-minutes: 30
    - if: ${{ contains(matrix.MAKE, 'O0=1 SANITIZE=1 LONG=1') }}
      name: make verify
      run:  ${{ matrix.MAKE }} verify
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
    - run:  nmake -f Makefile.win all
  macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - run:  make CXX='c++ -std=c++17'
